# Generated by Django 6.0.5 on 2026-05-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('morning_task', models.TextField()),
                ('prelunch_task', models.TextField()),
                ('postlunch_task', models.TextField()),
                ('report_date', models.DateField()),
                ('reminder_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
